// Code generated by hertz generator.

package event

import (
	"context"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	event "judgeMore/biz/model/event"
)

// UploadEventFile .
// @router /api/update/events/file [POST]
func UploadEventFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.UploadEventFileRequest
	data, err := c.FormFile("file")
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "required file but found not "+err.Error()))
		return
	}
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(event.UploadEventFileResponse)
	event_id, err := service.NewEventService(ctx, c).UploadEventFile(data)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.EventID = event_id
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UploadEvent .
// @router /api/update/events/auto [POST]
func UploadEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.UploadEventRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(event.UploadEventResponse)

	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryEvent .
// @router /api/query/events/single [GET]
func QueryEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.QueryEventRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(event.QueryEventResponse)
	info, err := service.NewEventService(ctx, c).QueryEventByEventId(req.EventID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.Event(info)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryEventByStuIdFile .
// @router /api/query/events/stu [GET]
func QueryEventByStuIdFile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.QueryEventByStuIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(event.QueryEventByStuIdResponse)
	info, count, err := service.NewEventService(ctx, c).QueryEventByStuId()
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.EventList(info, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UpdateEventStatus .
// @router /api/examine/materials [GET]
func UpdateEventStatus(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.UpdateEventStatusRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(event.UpdateEventStatusResponse)
	userInfo, err := service.NewEventService(ctx, c).UpdateEventStatus(req.EventID, req.ExamineResults)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.Event(userInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// ReviseEventLevel .
// @router /api/update/event/level [POST]
func ReviseEventLevel(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.ReviseEventLevelRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(event.ReviseEventLevelResponse)
	err = service.NewEventService(ctx, c).UpdateEventLevel(req.EventID, req.EventLevel, req.AppealID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryBelongStuEvent .
// @router /api/admin/query/materials/stu [GET]
func QueryBelongStuEvent(ctx context.Context, c *app.RequestContext) {
	var err error
	var req event.QueryBelongStuEventRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(event.QueryBelongStuEventResponse)
	info, count, err := service.NewEventService(ctx, c).QueryBelongStuEvent(req.Status)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.EventList(info, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
