// Code generated by hertz generator.

package maintain

import (
	"context"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/biz/service/model"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	maintain "judgeMore/biz/model/maintain"
)

// QueryCollege .
// @router /api/admin/colleges [GET]
func QueryCollege(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.QueryAllCollegeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.QueryAllCollegeResponse)
	collegeInfo, total, err := service.NewMaintainService(ctx, c).QueryColleges(req.PageNum, req.PageSize)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.CollegeList(collegeInfo, total)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryMajorByCollegeId .
// @router /api/admin/majors [GET]
func QueryMajorByCollegeId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.QueryMajorByCollegeIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.QueryMajorByCollegeIdResponse)
	majorInfo, total, err := service.NewMaintainService(ctx, c).QueryMajorByCollegeId(req.CollegeID, req.PageNum, req.PageSize)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.MajorList(majorInfo, total)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UploadMajor .
// @router /api/admin/majors [POST]
func UploadMajor(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.UploadMajorRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.UploadMajorResponse)
	majorId, err := service.NewMaintainService(ctx, c).UploadMajor(req.MajorName, req.CollegeID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.MajorID = majorId
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UploadCollege .
// @router /api/admin/colleges [POST]
func UploadCollege(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.UploadCollegeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(maintain.UploadCollegeResponse)
	collegeId, err := service.NewMaintainService(ctx, c).UploadCollege(req.CollegeName)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.CollegeID = collegeId
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// AddUser .
// @router /api/admin/users [POST]
func AddUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.AddUserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(maintain.AddUserResponse)
	u := &model.User{
		Uid:      req.UserID,
		Password: req.Password,
		Email:    req.Email,
		UserName: req.Username,
		Role:     req.UserRole,
	}
	if req.College != nil {
		u.College = *req.College
	}
	userid, err := service.NewMaintainService(ctx, c).AddUser(u)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.UserID = userid
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// AddAdminObject .
// @router /api/admin/users/permission [POST]
func AddAdminObject(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.AddAdminObjectRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.AddAdminObjectResponse)
	r := &model.Relation{
		UserId: req.UserID,
	}
	if req.CollegeName == nil {
		if req.MajorName == nil || req.Grade == nil {
			pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing: college or majot must have one"))
		}
		r.MajorName = *req.MajorName
		r.Grade = *req.Grade
	} else {
		r.CollegeName = *req.CollegeName
	}
	err = service.NewMaintainService(ctx, c).AddAdminRelation(r)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// UploadRecognizedReward .
// @router /api/admin/reward/upload [POST]
func UploadRecognizedReward(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.UploadRecognizedRewardRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(maintain.UploadRecognizedRewardResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteRecognizeReward .
// @router /api/admin/reward/delete [DELETE]
func DeleteRecognizeReward(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.DeleteRecognizeRewardRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(maintain.DeleteRecognizeRewardResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryRecognizeReward .
// @router /api/admin/reward/query [GET]
func QueryRecognizeReward(ctx context.Context, c *app.RequestContext) {
	var err error
	var req maintain.QueryRecognizeRewardRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(maintain.QueryRecognizeRewardResponse)
	info, count, err := service.NewMaintainService(ctx, c).QueryRecognizedReward(req.PageNum, req.PageSize)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.RecognizedEventList(info, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
