// Code generated by hertz generator.

package feedback

import (
	"context"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	feedback "judgeMore/biz/model/feedback"
)

// UploadFeedback .
// @router /api/feedback/upload [POST]
func UploadFeedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feedback.UploadFeedbackRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(feedback.UploadFeedbackResponse)
	err = service.NewFeedbackService(ctx, c).NewFeedback(req.Type, req.Content)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryFeedback .
// @router /api/admin/feedback/query [GET]
func QueryFeedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feedback.QueryFeedbackRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(feedback.QueryFeedbackResponse)
	I, err := service.NewFeedbackService(ctx, c).QueryFeedback()
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.FeedbackList(I)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
