// Code generated by hertz generator.

package score

import (
	"context"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/pkg/errno"

	"github.com/cloudwego/hertz/pkg/app"
	score "judgeMore/biz/model/score"
)

// QueryScoreByScoreId .
// @router /api/query/score/id [GET]
func QueryScoreByScoreId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryScoreByScoreIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(score.QueryScoreByScoreIdResponse)
	recordInfo, err := service.NewScoreService(ctx, c).QueryScoreRecordByScoreId(req.ScoreID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ScoreRecord(recordInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryScoreByEventId .
// @router /api/query/score/material [GET]
func QueryScoreByEventId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryScoreByEventIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(score.QueryScoreByEventIdResponse)
	recordInfo, err := service.NewScoreService(ctx, c).QueryScoreRecordByEventId(req.EventID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ScoreRecord(recordInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryScoreByStuId .
// @router /api/query/score/material [GET]
func QueryScoreByStuId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryScoreByStuIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(score.QueryScoreByStuIdResponse)
	recordInfo, count, err := service.NewScoreService(ctx, c).QueryScoreRecordByStuId(req.StuID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ScoreRecordList(recordInfo, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
