// Code generated by hertz generator.

package score

import (
	"context"
	"judgeMore/biz/pack"
	"judgeMore/biz/service"
	"judgeMore/biz/service/model"
	"judgeMore/pkg/errno"

	score "judgeMore/biz/model/score"

	"github.com/cloudwego/hertz/pkg/app"
)

// QueryScoreByScoreId .
// @router /api/query/score/id [GET]
func QueryScoreByScoreId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryScoreByScoreIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(score.QueryScoreByScoreIdResponse)
	recordInfo, err := service.NewScoreService(ctx, c).QueryScoreRecordByScoreId(req.ScoreID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ScoreRecord(recordInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryScoreByEventId .
// @router /api/query/score/material [GET]
func QueryScoreByEventId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryScoreByEventIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}
	resp := new(score.QueryScoreByEventIdResponse)
	recordInfo, err := service.NewScoreService(ctx, c).QueryScoreRecordByEventId(req.EventID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ScoreRecord(recordInfo)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// QueryScoreByStuId .
// @router /api/query/score/material [GET]
func QueryScoreByStuId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryScoreByStuIdRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(score.QueryScoreByStuIdResponse)
	recordInfo, count, err := service.NewScoreService(ctx, c).QueryScoreRecordByStuId(req.StuID)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Data = pack.ScoreRecordList(recordInfo, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// ReviseScore .
// @router /api/update/score/id [POST]
func ReviseScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.ReviseEventScoreRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(score.ReviseEventScoreResponse)
	err = service.NewScoreService(ctx, c).ReviseScore(req.ResultID, req.Score)
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}

// ScoreRank .
// @router /api/score/query/rank [GET]
func ScoreRank(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.ScoreRankRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.SendFailResponse(c, errno.NewErrNo(errno.ParamMissingErrorCode, "param missing:"+err.Error()))
		return
	}

	resp := new(score.ScoreRankResponse)
	info, count, err := service.NewScoreService(ctx, c).ScoreRank(&model.ScoreRankReq{
		StuName: req.GetStuName(),
		College: req.GetCollege(),
		Grade:   req.GetGrade(),
	})
	if err != nil {
		pack.SendFailResponse(c, errno.ConvertErr(err))
		return
	}

	resp.Data = pack.StuScoreMessageList(info, count)
	resp.Base = pack.BuildBaseResp(errno.Success)
	pack.SendResponse(c, resp)
}
