// Code generated by hertz generator.

package event

import (
	"github.com/cloudwego/hertz/pkg/app"
	"judgeMore/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _eventsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryeventMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _queryeventbystuidfileMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _events0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadeventMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(2)
}

func _uploadeventfileMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}

func _materialsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _materials0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _examineMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateeventstatusMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}
