// Code generated by hertz generator.

package maintain

import (
	"github.com/cloudwego/hertz/pkg/app"
	"judgeMore/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycollegeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadcollegeMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(3)
}

func _querymajorbycollegeidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadmajorMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(3)
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adduserMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(3)
}

func _addadminobjectMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(3)
}

func _rewardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleterecognizerewardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadrecognizedrewardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reward0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadrewardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryrecognizerewardMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateruleMw() []app.HandlerFunc {
	// your code...
	return nil
}
