// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	appeal "judgeMore/biz/router/appeal"
	event "judgeMore/biz/router/event"
	feedback "judgeMore/biz/router/feedback"
	maintain "judgeMore/biz/router/maintain"
	model "judgeMore/biz/router/model"
	score "judgeMore/biz/router/score"
	user "judgeMore/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	feedback.Register(r)

	appeal.Register(r)

	maintain.Register(r)

	score.Register(r)

	event.Register(r)

	user.Register(r)

	model.Register(r)
}
