// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	event "judgeMore/biz/router/event"
	model "judgeMore/biz/router/model"
	score "judgeMore/biz/router/score"
	user "judgeMore/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	score.Register(r)

	event.Register(r)

	user.Register(r)

	model.Register(r)
}
