// Code generated by hertz generator.

package feedback

import (
	"github.com/cloudwego/hertz/pkg/app"
	"judgeMore/biz/router/auth"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfeedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedback0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadfeedbackMw() []app.HandlerFunc {
	// your code...
	return auth.Auth(1)
}
